### ISSUE TITLE
Shadowchat Does Not React To Payment

### ISSUE THREAD

**Issue by ChanoSan** [LukeSmithxyz/shadowchat#2]
(Note: I realize this is cloned from a sourcehut repo, but I didn't see a way to file issues there so I'm defaulting to here. If there's a better place to post this, I'll happily paste it there)

server-side:
 - OS: Ubuntu 20.04
 - Monero RPC Version: 0.17.3.0-release

local:
 - Tested Browsers: Firefox 99.0 and Ungoogled Chromium Version 95.0.4638.54 (both in Private / Incognito Mode to disable script blockers etc).

I installed and set up Shadowchat following the README instructions, and everything seemed to work okay. It rendered properly in the browser and displayed a QR code on clicking the Pay button.

I initially tested Shadowchat in Firefox. Sending a payment was technically successful, in that it's reflected in the blockchain and received successfully in the wallet proper. Shadowchat showed no reaction to this, however:

![image](https://user-images.githubusercontent.com/48997871/162912052-f407830b-9212-4d82-bc82-ec4565ad9725.png)

The "3s" in the screenshot above is, I assume, "three seconds" but it never counted down. "Waiting for payment" did not change, even after the transaction itself received 10 confirmations. Neither the /view page nor the /alert page showed any messages. I even went into the /log directory, but none of the three files there (alertqueue.csv, paid.log, and superchats.csv) had any content at all.

After this, I tested in Ungoogled Chromium. In this case, the /pay page recognized the payment, and notified as such on screen, and the message was reflected in both /view and /alert, as well as the logs serverside.

I ran a second test in each browser, with the same results, so I can confirm that this wasn't just a temporary settings hiccup. I haven't tested this with any other browsers, but I thought the payment recognition and confirmation would be happening on the server, not in the browser, so I'm a little confused as to why Firefox does not work but Chromium does.

**Comment by 32s4o82d389yd238ffaw** [comment]
were you sending from the same wallet that is receiving? In my testing it doesn't pick up transactions when a wallet sends to itself. Also the (3s) is the refresh interval for the payment check

**Comment by ChanoSan** [comment]
> were you sending from the same wallet that is receiving?

No, they were different wallets. I did notice that in Chromium, the "Waiting For Payment" notice tended to flicker every few seconds, as though it was checking an refreshing the message. In Firefox it remained perfectly static, and didn't seem to be doing any refreshing at all.

What I'm curious about is why an otherwise successful payment on the blockchain wasn't entered into the Superchat log. I could understand if a Browser issue caused it to simply not display properly client-side, but it seems like that client-side failure results in the entire system remaining stuck.

**Comment by 32s4o82d389yd238ffaw** [comment]
In firefox do you see a little box with the url flash in the bottom left every 3 seconds? If you can reproduce the issue can you right click the "Waiting for payment..." > This Frame > and Reload frame manually?

**Comment by ChanoSan** [comment]
> In firefox do you see a little box with the url flash in the bottom left every 3 seconds? 

I do not. There are no visible changes on any part of the page.

> If you can reproduce the issue can you right click the "Waiting for payment..." .. and Reload frame manually?

I can confirm that this resulted in successful recognition by Firefox. After clicking "Pay" and sending a payment, then confirming it was in the blockchain, I right-clicked on the frame and selected "Reload Frame". It immediately showed " 0.005 XMR Received! Superchat sent ". The /view logs reflect this as well.

Could this be a Firefox setting interfering with automatic reloading? Also, is the creation of a log entry contingent on a success message being displayed?

**Comment by 32s4o82d389yd238ffaw** [comment]
I just did a fresh install of firefox and it is refreshing fine for me

**Comment by ChanoSan** [comment]
It's possible some plugin or custom setting on my end is the fault. As I said, I've done everything in a Private Browsing window, which usually disables script blocker interference et al. But maybe I made a change in about:config that I don't remember anymore.

**Comment by LukeSmithxyz** [comment]
Closing this assuming it was an idiosyncratic issue. I've only used this in a pretty Firefox and haven't run into these issues myself.

**Comment by Ashdemai** [comment]
I have also had this issue while trying to donate, so this is definitely not a one-off. The way it made it go through was to refresh the frame and it then it sent the donation.

**Comment by ChanoSan** [comment]
The original repo at sourcehut seems to have addressed this issue:

"added button to manually check payments for browsers that dont respect the auto refresh of iframes"
https://git.sr.ht/~anon_/shadowchat/commit/4340b343304acbc94efd93b4d55e295d5c4ccc08

**Comment by Ashdemai** [comment]
Oh goodie.

**Comment by ChanoSan** [comment]
As an addendum to above, I tested the newer code in the same problem browser as before (Firefox), and the payment was detected without issue.

**Comment by LukeSmithxyz** [comment]
The fix has been added here too now.
